//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedWriterWPF {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextList() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeedWriterWPF.TextList", typeof(TextList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Моряки-подводники боролись со штормами, когда лодка всплывала, но порой им приходилось прилагать немалые усилия для того, чтобы остаться под водой. Именно в эти трудные минуты рождалась настоящая мужская дружба. И сплачивала подводников не столько угроза нападения врагов, сколько само море. Боевые столкновения с неприятелем были лишь яркими вспышками на фоне их нелегкой службы. Море было той средой, где они совершали свои подвиги. 
        ///Эта книга не пособие для профессиональных офицеров-подводников и не описани [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TextFile1 {
            get {
                return ResourceManager.GetString("TextFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прогрохотал выстрел, от которого задрожали верхушки деревьев. Над лодкой поднялось облако черного дыма. Стена желтой пыли закрыла мишень. Когда пыль осела, мы дружно заулыбались. Дымовая труба исчезла, а вместе с ней и все здание. Над тем местом, где оно стояло, летали встревоженные птицы. С чувством выполненного долга мы продолжили путь. 
        ///Через некоторое время пришло письмо от руководителя местного комитета по лесоводству, в котором говорилось о том, что в определенный день и час английская подводная лодк [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TextFile2 {
            get {
                return ResourceManager.GetString("TextFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пост наблюдения и связи сигнализирует нам мощной синей лампой. Нам передают сообщение от адмирала флота и указывают, куда причалить. Мы сигналим ответ, осторожно двигаясь за нашим чересчур независимым ведущим. В бухте много судов. Танкеры, кажущиеся то перегруженными, то недогруженными, десантные катера, крейсерские яхты, торговые суда, суда Красного Креста, испанские суда, удивляющие своей окраской мирного времени, - все они стоят покачиваясь на легком ветру и поблескивая в лучах заходящего солнца. 
        ///Наша  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TextFile3 {
            get {
                return ResourceManager.GetString("TextFile3", resourceCulture);
            }
        }
    }
}
